[target.x86_64-unknown-linux-gnu]
# This installs the headers inside the build container
pre-build = [
    "dpkg --add-architecture amd64 && apt-get update && apt-get install --no-install-recommends -y libasound2-dev:amd64"

#[target.x86_64-unknown-linux-gnu]
# CentOS7-compatible (portable) baseline
#image = "x86_64-unknown-linux-gnu:main-centos"

#pre-build = [
#  "yum -y install alsa-lib-devel pkgconfig"
#]
#
#[target.x86_64-unknown-linux-gnu.env]
#passthrough = [
#  "PKG_CONFIG_ALLOW_CROSS=1"
#]

#[target.x86_64-unknown-linux-gnu]
#image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:0.2.5"
#
#pre-build = [
#  "apt-get update",
#  "apt-get install -y libasound2-dev pkg-config",
#]
